name: Set up and install
description: "Sets up pnpm and Node.js, and performs a cached install"

# Due to a limitation in GitHub Actions, the repo or this file must always be
# checked out before this composite action is used.

runs:
  using: "composite"
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
    - name: Set up Node.js and pnpm cache
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        cache: "pnpm"
        node-version-file: ".nvmrc"
    - name: Install dependencies
      shell: bash
      run: |
        pnpm config set //npm.pkg.github.com/:_authToken ${{ github.token }}
        pnpm install
