version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.PACKAGES_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "[UL-142] "
    registries:
      - npm-github
    groups:
      # Groups minor and patch updates for less noise.
      minor-patch:
        update-types:
          - "minor"
          - "patch"
      # These need to be updated in the same PR.
      react:
        patterns:
          - "react"
          - "react-dom"
    schedule:
      interval: "weekly"
    ignore:
      # `sc-web-ui` is not yet compatible with newer versions.
      - dependency-name: "styled-components"
        update-types: ["version-update:semver-major"]
      # `@types/node` should match our Node.js version.
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "[UL-142] "
    schedule:
      interval: "weekly"
