version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.PACKAGES_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - npm-github
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
    ignore:
      # `sc-web-ui` is not yet compatible.
      - dependency-name: "styled-components"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
