env:
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_PLUGIN_S3_CACHE_BUCKET: "sc-buildkite-build-cache-sandpit-us-east-2"
  BUILDKITE_PLUGIN_S3_CACHE_PREFIX: "frontend-unified-library"
  CC_TEST_REPORTER_ID: "${CC_TEST_REPORTER_ID}"

steps:
  - label: ":pnpm: Install dependencies"
    command: .buildkite/run-with-docker.sh
    key: install
    plugins:
      - cache#v1.0.1:
          backend: s3
          compression: tgz
          manifest: pnpm-lock.yaml
          path: .pnpm-store
          restore: pipeline
          save: file
    agents:
      queue: general-sandpit-us-east-1

  # Jobs with branch-level caching

  - label: ":jest: Run unit tests"
    branches: "!main"
    depends_on: install
    command: .buildkite/run-with-docker.sh "pnpm test"
    plugins:
      - cache#v1.0.1:
          backend: s3
          compression: tgz
          manifest: pnpm-lock.yaml
          path: .pnpm-store
          restore: file
          save: branch
    agents:
      queue: general-sandpit-us-east-1

  - label: ":eslint: Run ESLint"
    branches: "!main"
    depends_on: install
    command: .buildkite/run-with-docker.sh "pnpm eslint"
    plugins:
      - cache#v1.0.1:
          backend: s3
          compression: tgz
          manifest: pnpm-lock.yaml
          path: .pnpm-store
          restore: file
          save: branch
    agents:
      queue: general-sandpit-us-east-1

  - label: ":typescript: Run TypeScript"
    branches: "!main"
    depends_on: install
    command: .buildkite/run-with-docker.sh "pnpm typecheck"
    plugins:
      - cache#v1.0.1:
          backend: s3
          compression: tgz
          manifest: pnpm-lock.yaml
          path: .pnpm-store
          restore: file
          save: branch
    agents:
      queue: general-sandpit-us-east-1

  - label: ":prettier: Run Prettier"
    branches: "!main"
    depends_on: install
    command: .buildkite/run-with-docker.sh "pnpm prettier"
    plugins:
      - cache#v1.0.1:
          backend: s3
          compression: tgz
          manifest: pnpm-lock.yaml
          path: .pnpm-store
          restore: file
          save: branch
    agents:
      queue: general-sandpit-us-east-1

  # Jobs with pipeline-level caching

  - label: ":jest: Run unit tests"
    branches: "main"
    depends_on: install
    command: |
      .buildkite/run-with-docker.sh "pnpm test"
    plugins:
      - cache#v1.0.1:
          backend: s3
          compression: tgz
          manifest: pnpm-lock.yaml
          path: .pnpm-store
          restore: file
          save: pipeline
    agents:
      queue: general-sandpit-us-east-1

  - label: ":eslint: Run ESLint"
    branches: "main"
    depends_on: install
    command: |
      .buildkite/run-with-docker.sh "pnpm eslint"
    plugins:
      - cache#v1.0.1:
          backend: s3
          compression: tgz
          manifest: pnpm-lock.yaml
          path: .pnpm-store
          restore: file
          save: pipeline
    agents:
      queue: general-sandpit-us-east-1

  - label: ":typescript: Run TypeScript"
    branches: "main"
    depends_on: install
    command: |
      .buildkite/run-with-docker.sh "pnpm typecheck"
    plugins:
      - cache#v1.0.1:
          backend: s3
          compression: tgz
          manifest: pnpm-lock.yaml
          path: .pnpm-store
          restore: file
          save: pipeline
    agents:
      queue: general-sandpit-us-east-1

  - label: ":prettier: Run Prettier"
    branches: "main"
    depends_on: install
    command: |
      .buildkite/run-with-docker.sh "pnpm prettier"
    plugins:
      - cache#v1.0.1:
          backend: s3
          compression: tgz
          manifest: pnpm-lock.yaml
          path: .pnpm-store
          restore: file
          save: pipeline
    agents:
      queue: general-sandpit-us-east-1
