import { TransportProvider } from "@bufbuild/connect-query";
import type { Messages } from "@lingui/core";
import { i18n } from "@lingui/core";
import { I18nProvider } from "@lingui/react";
import { GlobalStyle, maggie } from "@safetyculture/sc-web-ui";
import { ConfigProvider, defaultConfig } from "@safetyculture/sc-web-ui/react";
import {
  HydrationBoundary,
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { AppProps } from "next/app";
import { Noto_Sans } from "next/font/google";
import Head from "next/head";
import { useState } from "react";
import { ThemeProvider, createGlobalStyle } from "styled-components";
import type { PageWithLayout } from "#/components/layouts";
import { publicTransport } from "#/utils/s12/transport";
import { useLinguiInit } from "../pages-router-i18n";

const NextGlobalStyles = createGlobalStyle`
  body > div:first-child,
  div#__next,
  div#__next > main:first-child {
    height: 100%;
  }

  body {
    min-width: 20rem;
    color: ${(p) => p.theme.colors.surface.text.default};
  }
`;

const notoSans = Noto_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

interface ExtendedAppProps {
  dehydratedState: unknown;
  translation: Messages;
}

interface AppPropsWithLayout extends AppProps<ExtendedAppProps> {
  Component: PageWithLayout;
}

export default function App({ Component, pageProps }: AppPropsWithLayout) {
  const [queryClient] = useState(() => new QueryClient());
  useLinguiInit(pageProps.translation);

  const getLayout = Component.getLayout ?? ((page) => page);

  return (
    <>
      <Head>
        {/* eslint-disable-next-line lingui/no-unlocalized-strings -- Placeholder */}
        <title>SafetyCulture</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GlobalStyle />

      <I18nProvider i18n={i18n}>
        <ConfigProvider config={defaultConfig}>
          <ThemeProvider theme={maggie}>
            <NextGlobalStyles />
            <TransportProvider transport={publicTransport}>
              <QueryClientProvider client={queryClient}>
                <HydrationBoundary state={pageProps.dehydratedState}>
                  <main className={notoSans.className}>
                    {getLayout(<Component {...pageProps} />)}
                  </main>
                </HydrationBoundary>
                <ReactQueryDevtools />
              </QueryClientProvider>
            </TransportProvider>
          </ThemeProvider>
        </ConfigProvider>
      </I18nProvider>
    </>
  );
}
