name: Playwright

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    if: false
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: |
          pnpm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          pnpm install
      - name: Install Playwright browsers
        run: pnpm --filter unified-library-tests exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm --filter unified-library-tests e2e:headless
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
