name: Playwright

on:
  merge_group:
  pull_request:
  push:
    branches: [main]

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

permissions:
  actions: write
  contents: read
  packages: read

env:
  TURBO_REMOTE_ONLY: true
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  e2e:
    # Disabled for now
    if: false
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Configure and install
        uses: ./.github/actions/set-up
      - name: Install Playwright browsers
        run: pnpm --filter unified-library-tests exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm --filter unified-library-tests e2e:headless
      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
