name: Quality

on:
  merge_group:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read
  packages: read

env:
  TURBO_REMOTE_ONLY: true
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  commonality:
    name: Commonality
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Configure and install
        uses: ./.github/actions/set-up
      - name: Run Commonality
        run: pnpm commonality
  eslint:
    name: ESLint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Configure and install
        uses: ./.github/actions/set-up
      - name: Run ESLint
        run: pnpm eslint
  prettier:
    name: Prettier
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Configure and install
        uses: ./.github/actions/set-up
      - name: Run Prettier
        run: pnpm prettier
  typescript:
    name: TypeScript
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Configure and install
        uses: ./.github/actions/set-up
      - name: Run TypeScript
        run: pnpm typecheck
  unit-test:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Configure and install
        uses: ./.github/actions/set-up
      - name: Run unit tests
        run: pnpm test
